# Generated by Django 5.0.7 on 2024-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Our_prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                ("image", models.ImageField(upload_to="base", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Настройка нашей цены",
            },
        ),
    ]
