# Generated by Django 5.0.7 on 2024-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_our_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Our_gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "all",
                    models.ImageField(upload_to="base", verbose_name="все фотографии"),
                ),
                (
                    "dogs_and",
                    models.ImageField(upload_to="base", verbose_name="кошки и собаки"),
                ),
                ("other", models.ImageField(upload_to="base", verbose_name="наше")),
            ],
            options={
                "verbose_name_plural": "Настройки галлереи животных",
            },
        ),
    ]
