# Generated by Django 5.0.7 on 2024-07-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_our_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="имя")),
                ("gender", models.CharField(max_length=255, verbose_name="пол")),
                ("image", models.ImageField(upload_to="base", verbose_name="Фото")),
                (
                    "kastrasya",
                    models.CharField(max_length=155, verbose_name="кастрация"),
                ),
                ("age", models.CharField(max_length=255, verbose_name="возраст")),
            ],
            options={
                "verbose_name_plural": "добавить животных",
            },
        ),
    ]
