# Generated by Django 5.0.7 on 2024-07-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_animals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=155, verbose_name="email")),
                ("number", models.CharField(max_length=255, verbose_name="номер")),
                ("image", models.ImageField(upload_to="base", verbose_name="Фото")),
                (
                    "kastrasya",
                    models.CharField(max_length=155, verbose_name="кастрация"),
                ),
                ("age", models.CharField(max_length=255, verbose_name="возраст")),
            ],
            options={
                "verbose_name_plural": "добавить животных",
            },
        ),
    ]
