# Generated by Django 5.0.7 on 2024-07-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name_plural": "Контакты"},
        ),
    ]
